Created a menu and moved New game & Quit game to it
ThePhilgrim/minesweeper pull request #45
Opened 2021-01-24 20:21 UTC by ThePhilgrim

Removed sidebar buttons, changed y padding of sliders, changed width & height slider min value to 10

2021-01-24 20:24 UTC, Akuli requested changes

2021-01-24 20:24 UTC, Akuli commented on minesweeper.py
> +    top_menu_game.add_command(label="Quit Game       F10", command=quit_game)
Use `accelerator="F2"` instead of spaces

2021-01-24 20:24 UTC, Akuli commented on minesweeper.py
> +    top_menu_game.add_command(label="Quit Game", command=quit_game)
These should go to `top_menu`, not `top_menu_game`

2021-01-24 22:17 UTC, ThePhilgrim commented
pushed again

2021-01-25 08:29 UTC, Akuli requested changes

2021-01-25 08:29 UTC, Akuli commented on minesweeper.py
> +    top_menu.add_command(label="Quit Game", command=quit_game)
These are missing accelerators

2021-01-25 08:29 UTC, Akuli commented
I guess you could also make pressing F2 and F10 actually work, instead of just showing them in the menu. Something like this:

```
root.bind('<F2>', new_game)
```

For that to work, `new_game()` must be defined so that it can take an event as an argument. But it's currently called without an event, so we need to make the event optional:

```
def new_game(event=None):
    ...
```

2021-01-25 08:33 UTC, Akuli commented
Forgot to mention in review: `# Creates a top menu` comment is unnecessary and not helpful

2021-01-25 08:35 UTC, ThePhilgrim commented
> I guess you could also make pressing F2 and F10 actually work, instead of just showing them in the menu. Something like this:
> 
> ```
> root.bind('<F2>', new_game)
> ```
> 
> For that to work, `new_game()` must be defined so that it can take an event as an argument. But it's currently called without an event, so we need to make the event optional:
> 
> ```
> def new_game(event=None):
>     ...
> ```

I was working on this before going to bed yesterday, but could not find how to bind keys. I thought I would fix it today

2021-01-25 15:17 UTC, Akuli approved these changes

2021-01-25 15:27 UTC, merged